package com.cricket.cricky.model.match.enums;

public enum Award {
  PLAYER_OF_SERIES,
  BATTER_OF_SERIES,
  BOWLER_OF_SERIES,
  FIELDER_OF_SERIES,

  PLAYER_OF_THE_MATCH,

  MOST_SIX_HITTER,
  MOST_WICKER_TAKER,
  MOST_ECONOMICAL_BOWLER,
  MOST_CATCH_TAKEN
}
